from omh.agent.session.values import (
    branch_tip,
    branch_tip_inventory_prefix,
    entry_label,
    lane_config,
    lane_state,
    operation_meta,
    operation_result,
    operation_state,
    operation_tool_args,
    operation_tool_args_prefix,
    operation_tool_memo,
    operation_tool_memo_prefix,
    pending_assistant_frames,
    pending_entry,
    pending_tool_output,
    pending_tool_output_prefix,
    session_name,
)


def test_builtin_addresses_use_omh_namespace() -> None:
    addresses = [
        branch_tip("branch"),
        branch_tip_inventory_prefix(),
        session_name,
        entry_label("entry"),
        lane_config("lane"),
        lane_state("lane"),
        operation_result("operation"),
        operation_meta("operation"),
        operation_state("operation"),
        pending_assistant_frames("operation", "response"),
        operation_tool_args("operation", "step", 0),
        operation_tool_args_prefix("operation"),
        operation_tool_memo("operation", "invocation", "memo"),
        operation_tool_memo_prefix("operation"),
        pending_entry("entry"),
        pending_tool_output("operation", "invocation"),
        pending_tool_output_prefix("operation"),
    ]

    assert [address.namespace for address in addresses] == [
        "omh.branch.tip",
        "omh.branch.tip",
        "omh.session.name",
        "omh.entry.label",
        "omh.lane.config",
        "omh.lane.state",
        "omh.result",
        "omh.op.meta",
        "omh.op.state",
        "omh.pending.assistant_frame",
        "omh.op.tool_args",
        "omh.op.tool_args",
        "omh.op.tool_memo",
        "omh.op.tool_memo",
        "omh.pending.entry",
        "omh.pending.tool_output",
        "omh.pending.tool_output",
    ]
