"""Traditional in-process Agent API.

``omh.agent`` is the main entry point for the in-process Agent. Persistent
execution lives in the experimental :mod:`omh.agent.durable` namespace and is
not imported from here.
"""

from __future__ import annotations

from omh.agent.agent import Agent
from omh.agent.stream_fn import (
    clear_default_stream_fn,
    get_default_stream_fn,
    set_default_stream_fn,
)
from omh.agent.types import (
    AfterToolCall,
    AfterToolCallContext,
    AfterToolCallResult,
    AgentContext,
    AgentEndEvent,
    AgentEvent,
    AgentInitialState,
    AgentLoopTurnUpdate,
    AgentMessage,
    AgentOptions,
    AgentRequestUpdate,
    AgentStartEvent,
    AgentState,
    AgentTool,
    AgentToolCall,
    AgentToolExecute,
    AgentToolPrepareArguments,
    AgentToolResult,
    AgentToolUpdateCallback,
    AgentTurnContext,
    AgentTurnDecision,
    BeforeToolCall,
    BeforeToolCallContext,
    BeforeToolCallResult,
    ConvertToLlm,
    CustomAgentMessage,
    FinishTurn,
    GetApiKey,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    OnPayload,
    OnProviderStreamEvent,
    OnResponse,
    PrepareNextTurn,
    PrepareNextTurnWithContext,
    PrepareNextTurnWithSignal,
    PrepareRequest,
    PrepareRequestContext,
    QueueMode,
    StreamFn,
    ThinkingLevel,
    ToolExecutionEndEvent,
    ToolExecutionMode,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TransformContext,
    TurnEndEvent,
    TurnStartEvent,
    to_tool_declaration,
)

__all__ = [
    "AfterToolCall",
    "AfterToolCallContext",
    "AfterToolCallResult",
    "Agent",
    "AgentContext",
    "AgentEndEvent",
    "AgentEvent",
    "AgentInitialState",
    "AgentLoopTurnUpdate",
    "AgentMessage",
    "AgentOptions",
    "AgentRequestUpdate",
    "AgentStartEvent",
    "AgentState",
    "AgentTurnContext",
    "AgentTurnDecision",
    "AgentTool",
    "AgentToolCall",
    "AgentToolExecute",
    "AgentToolPrepareArguments",
    "AgentToolResult",
    "AgentToolUpdateCallback",
    "BeforeToolCall",
    "BeforeToolCallContext",
    "BeforeToolCallResult",
    "ConvertToLlm",
    "CustomAgentMessage",
    "FinishTurn",
    "GetApiKey",
    "MessageEndEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "OnPayload",
    "OnProviderStreamEvent",
    "OnResponse",
    "PrepareNextTurn",
    "PrepareNextTurnWithContext",
    "PrepareNextTurnWithSignal",
    "PrepareRequest",
    "PrepareRequestContext",
    "QueueMode",
    "StreamFn",
    "ThinkingLevel",
    "ToolExecutionEndEvent",
    "ToolExecutionMode",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "TransformContext",
    "TurnEndEvent",
    "TurnStartEvent",
    "clear_default_stream_fn",
    "get_default_stream_fn",
    "set_default_stream_fn",
    "to_tool_declaration",
]
