"""Traditional in-process Agent API.

``omh.agent`` is the main entry point for the in-process Agent. Persistent
execution lives in the experimental :mod:`omh.durable` namespace and is
not imported from here.
"""

from __future__ import annotations

from omh.agent.agent import Agent
from omh.agent.compaction import (
    CompactionFailure,
    CompactionResult,
    CompactionSettings,
)
from omh.agent.context import AgentContext
from omh.agent.event_stream import AgentEventStream
from omh.agent.events import (
    AgentEndEvent,
    AgentEvent,
    AgentEventSink,
    AgentSettledEvent,
    AgentStartEvent,
    CompactionEndEvent,
    CompactionStartEvent,
    HistoryCommitEvent,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    ModelChangeEvent,
    RetryEndEvent,
    RetryStartEvent,
    ThinkingLevelChangeEvent,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TurnEndEvent,
    TurnStartEvent,
)
from omh.agent.history import (
    AgentHistory,
    AgentHistoryEntry,
    AgentHistorySettings,
    CompactionHistoryEntry,
    ContextEditHistoryEntry,
    CustomMessageHistoryEntry,
    MessageHistoryEntry,
    ModelChangeHistoryEntry,
    ThinkingLevelChangeHistoryEntry,
    validate_history,
)
from omh.agent.hooks import (
    AfterToolCall,
    AfterToolCallContext,
    AfterToolCallResult,
    AgentLoopTurnUpdate,
    AgentRequestUpdate,
    AgentTurnContext,
    AgentTurnDecision,
    BeforeToolCall,
    BeforeToolCallContext,
    BeforeToolCallResult,
    FinishTurn,
    GetApiKey,
    PrepareNextTurn,
    PrepareNextTurnWithContext,
    PrepareNextTurnWithSignal,
    PrepareRequest,
    PrepareRequestContext,
)
from omh.agent.loop import (
    agent_loop,
    agent_loop_continue,
    run_agent_loop,
    run_agent_loop_continue,
)
from omh.agent.loop_config import AgentLoopConfig
from omh.agent.messages import (
    AgentMessage,
    CompactionSummaryMessage,
    ContextEditReplacement,
    ConvertToLlm,
    CustomAgentMessage,
    LoopApplicationMessage,
    LoopConvertToLlm,
    LoopMessage,
    LoopTransformContext,
    TransformContext,
)
from omh.agent.options import AgentOptions, QueueMode
from omh.agent.retry import RetryPolicy
from omh.agent.state import (
    AgentInitialState,
    AgentState,
)
from omh.agent.stream_fn import (
    StreamFn,
    clear_default_stream_fn,
    get_default_stream_fn,
    set_default_stream_fn,
)
from omh.agent.tools import (
    AgentTool,
    AgentToolCall,
    AgentToolExecute,
    AgentToolPrepareArguments,
    AgentToolResult,
    AgentToolUpdateCallback,
    ToolExecutionMode,
    to_tool_declaration,
)
from omh.llm.types import ModelThinkingLevel as ThinkingLevel
from omh.llm.types import OnPayload, OnProviderStreamEvent, OnResponse

__all__ = [
    "AfterToolCall",
    "AfterToolCallContext",
    "AfterToolCallResult",
    "Agent",
    "AgentContext",
    "AgentEndEvent",
    "AgentEvent",
    "AgentEventSink",
    "AgentEventStream",
    "AgentInitialState",
    "AgentHistory",
    "AgentHistoryEntry",
    "AgentHistorySettings",
    "AgentLoopConfig",
    "AgentLoopTurnUpdate",
    "AgentMessage",
    "AgentOptions",
    "AgentRequestUpdate",
    "AgentSettledEvent",
    "AgentStartEvent",
    "AgentState",
    "AgentTurnContext",
    "AgentTurnDecision",
    "AgentTool",
    "AgentToolCall",
    "AgentToolExecute",
    "AgentToolPrepareArguments",
    "AgentToolResult",
    "AgentToolUpdateCallback",
    "BeforeToolCall",
    "BeforeToolCallContext",
    "BeforeToolCallResult",
    "ConvertToLlm",
    "CompactionEndEvent",
    "CompactionFailure",
    "CompactionHistoryEntry",
    "CompactionResult",
    "CompactionSettings",
    "CompactionStartEvent",
    "CompactionSummaryMessage",
    "ContextEditHistoryEntry",
    "ContextEditReplacement",
    "CustomAgentMessage",
    "CustomMessageHistoryEntry",
    "LoopApplicationMessage",
    "LoopConvertToLlm",
    "LoopMessage",
    "LoopTransformContext",
    "FinishTurn",
    "GetApiKey",
    "HistoryCommitEvent",
    "MessageEndEvent",
    "MessageHistoryEntry",
    "ModelChangeHistoryEntry",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "ModelChangeEvent",
    "OnPayload",
    "OnProviderStreamEvent",
    "OnResponse",
    "PrepareNextTurn",
    "PrepareNextTurnWithContext",
    "PrepareNextTurnWithSignal",
    "PrepareRequest",
    "PrepareRequestContext",
    "QueueMode",
    "RetryPolicy",
    "RetryStartEvent",
    "RetryEndEvent",
    "StreamFn",
    "ThinkingLevel",
    "ThinkingLevelChangeEvent",
    "ThinkingLevelChangeHistoryEntry",
    "ToolExecutionEndEvent",
    "ToolExecutionMode",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "TransformContext",
    "TurnEndEvent",
    "TurnStartEvent",
    "agent_loop",
    "agent_loop_continue",
    "clear_default_stream_fn",
    "get_default_stream_fn",
    "run_agent_loop",
    "run_agent_loop_continue",
    "set_default_stream_fn",
    "to_tool_declaration",
    "validate_history",
]
