from __future__ import annotations

from omh.llm.auth.resolve import ModelsError
from omh.llm.models import (
    CreateModelsOptions,
    MutableModels,
    Provider,
    calculate_cost,
    clamp_thinking_level,
    create_models,
    create_provider,
    get_supported_thinking_levels,
    has_api,
    models_are_equal,
)
from omh.llm.providers.deepseek import deepseek_provider
from omh.llm.types import (
    AssistantMessage,
    AssistantMessageEvent,
    Context,
    DoneEvent,
    ErrorEvent,
    FetchRequest,
    FetchResponse,
    ImageContent,
    Message,
    Model,
    SimpleStreamOptions,
    StartEvent,
    TextContent,
    TextDeltaEvent,
    TextEndEvent,
    TextStartEvent,
    ThinkingContent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingStartEvent,
    Tool,
    ToolCall,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
    ToolResultMessage,
    Usage,
    UserMessage,
    empty_usage,
)
from omh.llm.utils.assistant_message_frame import (
    AssistantMessageFrame,
    AssistantMessageFrameEncoder,
    reduce_assistant_message_frames,
)
from omh.llm.utils.event_stream import AssistantMessageEventStream
from omh.llm.utils.text import content_text

__all__ = [
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantMessageEventStream",
    "AssistantMessageFrame",
    "AssistantMessageFrameEncoder",
    "Context",
    "CreateModelsOptions",
    "DoneEvent",
    "ErrorEvent",
    "FetchRequest",
    "FetchResponse",
    "ImageContent",
    "Message",
    "Model",
    "ModelsError",
    "MutableModels",
    "Provider",
    "SimpleStreamOptions",
    "StartEvent",
    "TextContent",
    "TextDeltaEvent",
    "TextEndEvent",
    "TextStartEvent",
    "ThinkingContent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ThinkingStartEvent",
    "Tool",
    "ToolCall",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "ToolCallStartEvent",
    "ToolResultMessage",
    "Usage",
    "UserMessage",
    "calculate_cost",
    "clamp_thinking_level",
    "content_text",
    "create_models",
    "create_provider",
    "deepseek_provider",
    "empty_usage",
    "get_supported_thinking_levels",
    "has_api",
    "models_are_equal",
    "reduce_assistant_message_frames",
]
